package workflow

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"math/rand/v2"
	"strings"
	"sync"
	"time"

	"github.com/deepnoodle-ai/workflow/script"
)

// catchErrorSentinel is a sentinel value used to indicate that a catch handler
// executed and the current step has been updated.
const catchErrorSentinel = "__CATCH_HANDLED__"

// pauseStepSentinel is a sentinel value returned by handlePauseStep to
// indicate that a declarative Pause step has advanced currentStep past
// itself and set the runtime pause flag. branch.Run catches the sentinel
// and continues the loop; the top-of-loop pause check then emits the
// Paused snapshot referencing the already-advanced step.
const pauseStepSentinel = "__PAUSE_STEP_TRIGGERED__"

// activityExecutor provides a simplified interface for executing activities with logging and checkpointing
type activityExecutor interface {
	// ExecuteActivity runs an activity with automatic logging and checkpointing
	// In the new branch-local state system, activities work directly with branch state
	ExecuteActivity(ctx context.Context, stepName, branchID string, activity Activity, params map[string]interface{}, branchState *BranchLocalState) (result interface{}, err error)
}

// branchOptions contains all dependencies needed by a branch, injected at construction
type branchOptions struct {
	Workflow           *Workflow
	ActivityRegistry   map[string]Activity
	Logger             *slog.Logger
	Inputs             map[string]any // Initial inputs (readonly)
	Variables          map[string]any // Initial variables (will be copied)
	activityExecutor   activityExecutor
	UpdatesChannel     chan<- branchSnapshot
	ScriptCompiler     script.Compiler
	ExecutionCallbacks ExecutionCallbacks

	// SignalStore and ExecutionID are plumbed so declarative WaitSignal
	// steps (which don't run through executeActivity) can reach the
	// signal infrastructure directly. Both may be nil for workflows that
	// never use signals.
	SignalStore SignalStore
	ExecutionID string

	// InitialWait is the pending wait state the branch was checkpointed
	// on, if any. Populated by the engine when a suspended branch is
	// being restarted so declarative WaitSignal steps can reuse the
	// original absolute deadline across replay cycles.
	InitialWait *WaitState

	// InitialPauseRequested seeds the runtime pause flag when a branch
	// is being reconstructed from a checkpoint with PauseRequested=true.
	// The branch will re-park at its first step boundary unless the
	// flag is cleared via UnpauseBranch before Run is called.
	InitialPauseRequested bool
	// InitialPauseReason seeds the runtime pause reason alongside
	// InitialPauseRequested. Ignored when InitialPauseRequested is false.
	InitialPauseReason string
}

// branchSpec specifies how to create a new branch (ID generated by Execution)
type branchSpec struct {
	Step      *Step
	Variables map[string]any
	Name      string // Optional name for the branch from Edge.branch
}

// branchSnapshot represents a snapshot of branch state for communication
type branchSnapshot struct {
	BranchID     string
	Status       ExecutionStatus
	StepName     string
	StepOutput   any
	NewBranches  []branchSpec
	Error        error
	Timestamp    time.Time
	StartTime    time.Time
	EndTime      time.Time
	joinRequest  *joinRequest  // New field for join requests
	waitRequest  *waitRequest  // Spike: branch is parking to wait for a signal
	pauseRequest *pauseRequest // branch is parking due to a pause trigger
}

// waitRequest indicates a branch is hard-suspending on a durable wait
// (workflow.Wait signal, declarative WaitSignal step, or Sleep step).
// The branch goroutine has exited; the orchestrator will persist Wait in
// the branch state, checkpoint, and exit the run loop when no running
// branches remain.
type waitRequest struct {
	StepName string
	Wait     *WaitState
}

// joinRequest indicates a branch is waiting at a join step
type joinRequest struct {
	StepName    string         `json:"step_name"`
	Config      *JoinConfig    `json:"config"`
	Variables   map[string]any `json:"variables"`
	StepOutputs map[string]any `json:"step_outputs"`
}

// branch represents an execution branch through a workflow with owned state
type branch struct {
	// Owned state
	id          string
	currentStep *Step
	status      ExecutionStatus
	stepOutputs map[string]any
	startTime   time.Time
	endTime     time.Time
	state       *BranchLocalState

	// Join coordination
	resumeFromJoin chan struct{} // Channel to signal resumption from join

	// Pause coordination
	pauseMu     sync.Mutex
	paused      bool
	pauseReason string

	// Signal infrastructure (optional — nil when the execution has no
	// SignalStore configured).
	signalStore SignalStore
	executionID string
	initialWait *WaitState

	// Injected dependencies (immutable after construction)
	workflow           *Workflow
	activityRegistry   map[string]Activity
	activityExecutor   activityExecutor
	logger             *slog.Logger
	updates            chan<- branchSnapshot
	scriptCompiler     script.Compiler
	executionCallbacks ExecutionCallbacks
}

// newBranch creates a new execution branch with options pattern
func newBranch(id string, step *Step, opts branchOptions) *branch {
	logger := opts.Logger
	if logger == nil {
		logger = slog.New(slog.NewTextHandler(io.Discard, nil))
	}
	logger = logger.With("branch_id", id)

	state := NewBranchLocalState(opts.Inputs, opts.Variables)

	p := &branch{
		id:                 id,
		currentStep:        step,
		status:             ExecutionStatusPending,
		stepOutputs:        make(map[string]any),
		state:              state,
		resumeFromJoin:     make(chan struct{}, 1), // Buffered channel for join resumption
		signalStore:        opts.SignalStore,
		executionID:        opts.ExecutionID,
		initialWait:        opts.InitialWait,
		workflow:           opts.Workflow,
		activityRegistry:   opts.ActivityRegistry,
		activityExecutor:   opts.activityExecutor,
		logger:             logger,
		updates:            opts.UpdatesChannel,
		scriptCompiler:     opts.ScriptCompiler,
		executionCallbacks: opts.ExecutionCallbacks,
	}
	if opts.InitialPauseRequested {
		p.paused = true
		p.pauseReason = opts.InitialPauseReason
	}
	return p
}

// requestPause marks the branch as paused. The pause will take effect at
// the next step boundary in branch.Run. Safe to call from any goroutine.
func (p *branch) requestPause(reason string) {
	p.pauseMu.Lock()
	defer p.pauseMu.Unlock()
	p.paused = true
	p.pauseReason = reason
}

// clearPause clears a pending pause request. Safe to call from any
// goroutine. Has no effect if the branch has already observed the flag
// and exited.
func (p *branch) clearPause() {
	p.pauseMu.Lock()
	defer p.pauseMu.Unlock()
	p.paused = false
	p.pauseReason = ""
}

// checkPause returns whether a pause has been requested and the
// recorded reason, without clearing the flag.
func (p *branch) checkPause() (bool, string) {
	p.pauseMu.Lock()
	defer p.pauseMu.Unlock()
	return p.paused, p.pauseReason
}

// ID returns the branch ID
func (p *branch) ID() string {
	return p.id
}

// CurrentStep returns the current step in the branch
func (p *branch) CurrentStep() *Step {
	return p.currentStep
}

// Variables returns a copy of the branch's current variables
func (p *branch) Variables() map[string]any {
	p.state.mu.RLock()
	defer p.state.mu.RUnlock()
	return copyMap(p.state.variables)
}

// Run executes the branch until completion or error
func (p *branch) Run(ctx context.Context) error {
	p.status = ExecutionStatusRunning
	p.startTime = time.Now()

	for {
		// Check for context cancellation
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		// Check for a pending pause request. A paused branch emits a
		// pauseRequest snapshot and exits cleanly — the orchestrator
		// persists Status=Paused and removes the branch from
		// activeBranches, just like a wait-unwind. On resume, the branch
		// will be reconstructed with InitialPauseRequested=true and
		// re-park here until UnpauseBranch clears the flag.
		if paused, reason := p.checkPause(); paused {
			p.status = ExecutionStatusPaused
			p.endTime = time.Now()
			p.updates <- branchSnapshot{
				BranchID: p.id,
				Status:   ExecutionStatusPaused,
				StepName: p.currentStep.Name,
				pauseRequest: &pauseRequest{
					StepName: p.currentStep.Name,
					Reason:   reason,
				},
				StartTime: p.startTime,
				EndTime:   p.endTime,
				Timestamp: time.Now(),
			}
			return nil
		}

		// Execute the current step
		currentStep := p.currentStep
		result, err := p.executeStep(ctx, currentStep)
		if err != nil {
			// Detect wait-unwind and park the branch instead of failing.
			// The orchestrator will mark state as Suspended, checkpoint,
			// and exit when no running branches remain.
			if wu, ok := asWaitUnwind(err); ok {
				// Pause-during-wait race: an external PauseBranch call
				// may have arrived while the activity was running and
				// unwinding. Pause wins — drop the (un-checkpointed)
				// wait state and park the branch as Paused. On unpause +
				// resume the activity will replay from the top with a
				// fresh deadline, which is the right behavior because
				// the operator pause should not consume timeout budget
				// for a wait that never even reached the checkpoint.
				if paused, reason := p.checkPause(); paused {
					p.status = ExecutionStatusPaused
					p.endTime = time.Now()
					p.updates <- branchSnapshot{
						BranchID: p.id,
						Status:   ExecutionStatusPaused,
						StepName: currentStep.Name,
						pauseRequest: &pauseRequest{
							StepName: currentStep.Name,
							Reason:   reason,
						},
						StartTime: p.startTime,
						EndTime:   p.endTime,
						Timestamp: time.Now(),
					}
					return nil
				}
				p.status = ExecutionStatusSuspended
				p.endTime = time.Now()
				p.updates <- branchSnapshot{
					BranchID: p.id,
					Status:   ExecutionStatusSuspended,
					StepName: currentStep.Name,
					waitRequest: &waitRequest{
						StepName: currentStep.Name,
						Wait:     wu.Wait,
					},
					StartTime: p.startTime,
					EndTime:   p.endTime,
					Timestamp: time.Now(),
				}
				return nil
			}
			p.status = ExecutionStatusFailed
			p.endTime = time.Now()
			p.updates <- branchSnapshot{
				BranchID:  p.id,
				Status:    p.status,
				StepName:  currentStep.Name,
				Error:     err,
				StartTime: p.startTime,
				EndTime:   p.endTime,
				Timestamp: time.Now(),
			}
			return err
		}

		// Handle join completion - continue normal execution
		if result == "join_completed" {
			// The join completed and this branch was resumed
			// Continue with normal execution flow (don't store output for join step)
			continue
		}

		// Handle catch handler results specially
		if result == catchErrorSentinel {
			// Catch handler was executed, current step has been updated
			// Continue with the new step without storing output or handling branching
			continue
		}

		// Handle pause-step results specially. The handler has already
		// set the pause flag and advanced currentStep past the pause
		// step. Continue the loop so the top-of-loop pause check
		// emits the Paused snapshot.
		if result == pauseStepSentinel {
			continue
		}

		// Store step output
		p.stepOutputs[currentStep.Name] = result

		// Handle branch branching (state is now current)
		newBranchSpecs, err := p.handleBranching(ctx)
		if err != nil {
			p.status = ExecutionStatusFailed
			p.endTime = time.Now()
			p.updates <- branchSnapshot{
				BranchID:  p.id,
				Status:    p.status,
				StepName:  currentStep.Name,
				Error:     err,
				StartTime: p.startTime,
				EndTime:   p.endTime,
				Timestamp: time.Now(),
			}
			return err
		}

		// This branch is complete if there are:
		//  A) no new branches
		//  B) multiple branches (branching)
		//  C) single branch with a PathName that differs from current branch (named branch to different branch)
		hasNamedBranches := len(newBranchSpecs) > 0 && newBranchSpecs[0].Name != ""
		sameBranchName := hasNamedBranches && newBranchSpecs[0].Name == p.id
		isDone := len(newBranchSpecs) == 0 || len(newBranchSpecs) > 1 || (hasNamedBranches && !sameBranchName)

		if isDone {
			p.status = ExecutionStatusCompleted
			p.endTime = time.Now()
		}

		// Send snapshot update
		var pathsToCreate []branchSpec
		if len(newBranchSpecs) > 1 || (hasNamedBranches && !sameBranchName) {
			pathsToCreate = newBranchSpecs
		}

		p.updates <- branchSnapshot{
			BranchID:    p.id,
			Status:      p.status,
			StepName:    currentStep.Name,
			StepOutput:  result,
			NewBranches: pathsToCreate,
			StartTime:   p.startTime,
			EndTime:     p.endTime,
			Timestamp:   time.Now(),
		}

		if isDone {
			return nil
		}

		// Continue with the single branch (only if it's unnamed)
		p.currentStep = newBranchSpecs[0].Step
	}
}

// executeStep executes a single workflow step
func (p *branch) executeStep(ctx context.Context, step *Step) (any, error) {
	p.logger.Debug("executing step", "step_name", step.Name)

	// Check if this is a join step
	if step.Join != nil {
		return p.handleJoinStep(ctx, step)
	}

	// Check if this is a wait-signal step (declarative signal wait).
	if step.WaitSignal != nil {
		return p.handleWaitSignalStep(ctx, step)
	}

	// Check if this is a durable Sleep step.
	if step.Sleep != nil {
		return p.handleSleepStep(ctx, step)
	}

	// Check if this is a declarative Pause step.
	if step.Pause != nil {
		return p.handlePauseStep(ctx, step)
	}

	var result any
	var err error

	// Execute with retry logic if configured
	retryConfigs := step.Retry
	if len(retryConfigs) > 0 {
		result, err = p.executeStepWithRetry(ctx, step, retryConfigs)
	} else {
		result, err = p.executeStepOnce(ctx, step)
	}

	if err != nil {
		// Wait-unwind bypasses catch: a suspension is not a failure, and
		// routing it through a catch handler would silently drop it on
		// the floor. Explicit bypass mirrors ErrFenceViolation's bypass
		// and is safer than relying on ErrorType non-matching.
		if isWaitUnwind(err) {
			return nil, err
		}
		// Try catch handlers for any step failure
		if len(step.Catch) > 0 {
			catchResult, catchErr := p.executeCatchHandler(step, err)
			if catchErr == nil {
				return catchResult, nil
			}
			// If catch handler also fails, return original error
		}
		return nil, err
	}

	// Store step result in branch-local state if not an each step (each steps handle their own storage)
	if step.Each == nil {
		// Store the result in a state variable if specified
		if varName := step.Store; varName != "" {
			// Strip "state." prefix if present
			varName = strings.TrimPrefix(varName, "state.")

			// Store the result directly in branch variables
			var valueToStore interface{}
			if result != nil {
				valueToStore = result
			}
			p.state.Set(varName, valueToStore)
		}
	}

	return result, nil
}

// handleWaitSignalStep executes a declarative WaitSignal step.
//
// Behavior (matches workflow.Wait):
//   - Evaluate the topic template against current branch state. The resolved
//     topic is what's registered with the SignalStore and persisted in
//     WaitState.Topic.
//   - Check the SignalStore for an already-delivered signal and consume it
//     if present (store payload in the step's Store variable, advance).
//   - If the branch is being replayed after a resume, reuse the original
//     absolute deadline from p.initialWait rather than restarting the clock.
//   - If the deadline has passed: route to OnTimeout if set, otherwise
//     fail the step with ErrorTypeTimeout.
//   - Otherwise, return a waitUnwindError with the (possibly reused) wait
//     state; branch.Run translates the sentinel into a waitRequest snapshot
//     and the orchestrator hard-suspends the branch.
func (p *branch) handleWaitSignalStep(ctx context.Context, step *Step) (any, error) {
	cfg := step.WaitSignal
	if cfg == nil {
		return nil, fmt.Errorf("wait_signal step %q missing configuration", step.Name)
	}
	if cfg.Topic == "" {
		return nil, fmt.Errorf("wait_signal step %q: topic is required", step.Name)
	}
	if cfg.Timeout <= 0 {
		return nil, fmt.Errorf("wait_signal step %q: positive timeout is required", step.Name)
	}
	if p.signalStore == nil {
		return nil, fmt.Errorf("wait_signal step %q: no SignalStore configured on execution", step.Name)
	}

	// Consume the initial wait exactly once: the checkpointed wait
	// belongs to the step that was suspended. Any later step that
	// runs in this same resumed branch must start from a fresh clock.
	initial := p.initialWait
	p.initialWait = nil

	// Resolve the topic template against current state.
	var resolvedTopic string
	if initial != nil && initial.Kind == WaitKindSignal && initial.Topic != "" {
		// Reuse the resolved topic from the original suspension so template
		// re-evaluation on replay can't drift.
		resolvedTopic = initial.Topic
	} else {
		evaluated, err := p.evaluateTemplateString(ctx, cfg.Topic)
		if err != nil {
			return nil, fmt.Errorf("wait_signal step %q: failed to evaluate topic template: %w", step.Name, err)
		}
		resolvedTopic = evaluated
	}
	if resolvedTopic == "" {
		return nil, fmt.Errorf("wait_signal step %q: resolved topic is empty", step.Name)
	}

	// Consult the store first so an already-delivered signal wins.
	sig, err := p.signalStore.Receive(ctx, p.executionID, resolvedTopic)
	if err != nil {
		return nil, fmt.Errorf("wait_signal step %q: receive failed: %w", step.Name, err)
	}
	if sig != nil {
		// Deliver the payload to the configured store variable, then
		// advance past the step. branch.Run treats a non-error return as
		// normal progress; processBranchSnapshot will clear BranchState.Wait.
		if cfg.Store != "" {
			varName := strings.TrimPrefix(cfg.Store, "state.")
			p.state.Set(varName, sig.Payload)
		}
		return sig.Payload, nil
	}

	// Build / reuse wait state. On replay, reuse the deadline from the
	// checkpoint; on first entry, compute a new absolute deadline.
	var ws *WaitState
	if initial != nil && initial.Kind == WaitKindSignal && initial.Topic == resolvedTopic {
		reused := *initial
		ws = &reused
	} else {
		ws = newSignalWait(resolvedTopic, cfg.Timeout)
	}

	// Belt-and-suspenders: a frozen wait (WakeAt zero, Remaining > 0)
	// can reach this handler if a checkpoint edit or partial unpause
	// left the deadline un-thawed. Rebase to now + Remaining so the
	// wait has a real deadline rather than running forever.
	if ws.WakeAt.IsZero() && ws.Remaining > 0 {
		ws.WakeAt = time.Now().Add(ws.Remaining)
		ws.Remaining = 0
	}

	// Check the absolute deadline: route or fail if already expired.
	if !ws.WakeAt.IsZero() && !time.Now().Before(ws.WakeAt) {
		if cfg.OnTimeout != "" {
			nextStep, ok := p.workflow.GetStep(cfg.OnTimeout)
			if !ok {
				return nil, fmt.Errorf("wait_signal step %q: OnTimeout target %q not found", step.Name, cfg.OnTimeout)
			}
			// Route to the timeout successor in-place and continue the
			// run loop. Mirrors how executeCatchHandler advances
			// p.currentStep and returns the catchErrorSentinel.
			p.currentStep = nextStep
			p.logger.Info("wait_signal timed out, routing to OnTimeout",
				"step_name", step.Name,
				"on_timeout", cfg.OnTimeout)
			return catchErrorSentinel, nil
		}
		return nil, NewWorkflowError(ErrorTypeTimeout,
			fmt.Sprintf("wait_signal step %q: timed out on topic %q", step.Name, resolvedTopic))
	}

	// Suspend: return the unwind sentinel. branch.Run sends a waitRequest
	// snapshot and the orchestrator checkpoints + exits the run loop.
	return nil, &waitUnwindError{Wait: ws}
}

// handleSleepStep executes a durable Sleep step.
//
// The step computes an absolute WakeAt from SleepConfig.Duration at
// first entry and hard-suspends the branch. On resume before the
// deadline the branch re-suspends with the same absolute deadline; on
// resume at or after the deadline the handler returns normally and
// the branch advances to the successor step.
//
// Pause interaction: when a sleeping branch is paused via PauseBranch, the
// sleep clock freezes (remaining duration is captured and WakeAt is
// cleared). On unpause, WakeAt is recomputed as now + remaining. The
// handler reconstructs the wait from initialWait if present, so the
// updated WakeAt is honored across the replay.
func (p *branch) handleSleepStep(ctx context.Context, step *Step) (any, error) {
	cfg := step.Sleep
	if cfg == nil {
		return nil, fmt.Errorf("sleep step %q missing configuration", step.Name)
	}
	if cfg.Duration <= 0 {
		return nil, fmt.Errorf("sleep step %q: positive duration is required", step.Name)
	}

	// Consume the initial wait exactly once: the checkpointed wait
	// belongs to the step that was suspended. Any later Sleep step
	// in this same resumed branch must start from a fresh clock rather
	// than reusing the prior step's deadline.
	initial := p.initialWait
	p.initialWait = nil

	// Reuse the checkpointed wait on replay so the absolute deadline
	// carries across resumes. First entry constructs a fresh one from
	// the configured Duration.
	var ws *WaitState
	if initial != nil && initial.Kind == WaitKindSleep {
		reused := *initial
		ws = &reused
	} else {
		ws = newSleepWait(cfg.Duration)
	}

	// If Remaining is populated (branch was paused mid-sleep but the
	// wait state wasn't rebased by UnpauseBranch for whatever reason),
	// rebase the absolute deadline now. This is a belt-and-suspenders
	// guard so a manual checkpoint edit or a partial unpause cannot
	// leave a Sleep wait stuck with no WakeAt.
	if ws.WakeAt.IsZero() && ws.Remaining > 0 {
		ws.WakeAt = time.Now().Add(ws.Remaining)
		ws.Remaining = 0
	}

	// If the deadline has passed, wake immediately. The handler
	// returns a nil result so branch.Run stores no step output and
	// advances via the normal branching logic.
	if !ws.WakeAt.IsZero() && !time.Now().Before(ws.WakeAt) {
		p.logger.Info("sleep complete, advancing", "step_name", step.Name)
		return nil, nil
	}

	// Deadline not yet reached: hard-suspend. Reuse waitUnwindError so
	// the existing suspension machinery (snapshot → orchestrator →
	// checkpoint) handles sleeps identically to signal waits.
	return nil, &waitUnwindError{Wait: ws}
}

// handlePauseStep executes a declarative Pause step.
//
// The step advances currentStep past itself (via the Next edges) and
// sets the runtime pause flag. It then returns pauseStepSentinel so
// branch.Run continues the loop; the top-of-loop pause check picks up
// the flag and emits a Paused snapshot referencing the already-advanced
// successor step. On unpause + resume, the branch continues at that
// successor rather than re-entering the Pause step.
//
// A Pause step may have at most one matching Next edge. Zero matching
// edges is allowed and means "pause is a terminal hold point" — after
// unpause the branch completes. Multiple matching edges are rejected
// because a pause is a single-choice gate, not a branch point.
func (p *branch) handlePauseStep(ctx context.Context, step *Step) (any, error) {
	cfg := step.Pause
	if cfg == nil {
		return nil, fmt.Errorf("pause step %q missing configuration", step.Name)
	}

	specs, err := p.handleBranching(ctx)
	if err != nil {
		return nil, fmt.Errorf("pause step %q: %w", step.Name, err)
	}
	if len(specs) > 1 {
		return nil, fmt.Errorf("pause step %q: multiple next edges are not supported", step.Name)
	}
	if len(specs) == 1 {
		// A pause step is a single-choice gate on the current branch,
		// not a branch point. A named edge (Edge.branch) would normally
		// spawn a new named branch and complete the current one, which
		// is incompatible with the pause semantics of "park this branch
		// here, resume it later at the successor." Reject explicitly
		// rather than silently dropping the name.
		if specs[0].Name != "" {
			return nil, fmt.Errorf("pause step %q: named edges (Edge.branch = %q) are not supported — a pause step is a single-choice gate on the current branch, not a branch point", step.Name, specs[0].Name)
		}
		// Advance past the pause step so resume lands at the successor.
		p.currentStep = specs[0].Step
		// Carry forward the matched edge's variables so any branching
		// state transforms are preserved.
		if specs[0].Variables != nil {
			for k, v := range specs[0].Variables {
				p.state.Set(k, v)
			}
		}
	}
	// A pause step with zero matching edges (or none defined) is a
	// terminal hold: after unpause the branch has no successor and
	// completes. We leave p.currentStep at the pause step so the
	// Paused snapshot references it; on unpause + resume, the branch
	// reconstructs, starts at the pause step, re-enters this handler,
	// and after the top-of-loop check clears re-executes here with
	// the pause flag cleared. To avoid an infinite re-trigger loop
	// in that case, reject a pause step with no successors as a
	// configuration error — the author should place the pause on a
	// step that has a successor, or end the workflow before the
	// pause.
	if len(specs) == 0 {
		return nil, fmt.Errorf("pause step %q: a pause step must have at least one reachable Next edge", step.Name)
	}

	p.requestPause(cfg.Reason)
	return pauseStepSentinel, nil
}

// handleJoinStep handles execution of a join step
func (p *branch) handleJoinStep(ctx context.Context, step *Step) (any, error) {
	p.logger.Debug("handling join step", "step_name", step.Name, "join_config", step.Join)

	// Create join request with current branch state
	joinRequest := &joinRequest{
		StepName:    step.Name,
		Config:      step.Join,
		Variables:   p.Variables(),
		StepOutputs: copyMap(p.stepOutputs),
	}

	// Send join request via branch snapshot
	p.updates <- branchSnapshot{
		BranchID:    p.id,
		Status:      ExecutionStatusWaiting, // Mark as waiting instead of running
		StepName:    step.Name,
		StepOutput:  nil, // No output yet
		joinRequest: joinRequest,
		StartTime:   p.startTime,
		Timestamp:   time.Now(),
	}

	p.logger.Debug("sent join request, waiting for other branches", "step_name", step.Name)

	// Wait for the join to complete and this branch to be resumed
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	case <-p.resumeFromJoin:
		p.logger.Debug("resumed from join", "step_name", step.Name)
		// The branch's variables have been updated with merged state by the execution
		// Continue normally - the current step will be updated by the execution
		return "join_completed", nil
	}
}

// executeStepOnce executes a step once without retry logic
func (p *branch) executeStepOnce(ctx context.Context, step *Step) (any, error) {
	// Handle steps with "each" blocks
	if step.Each != nil {
		return p.executeStepEach(ctx, step)
	}

	// Use Activity interface
	activityName := step.Activity
	if activityName == "" {
		return nil, fmt.Errorf("no activity specified for step %q", step.Name)
	}

	// Look up activity in registry
	activity, ok := p.activityRegistry[activityName]
	if !ok {
		return nil, fmt.Errorf("activity %q not found for step %q", activityName, step.Name)
	}

	// Prepare parameters by evaluating templates and script expressions.
	// A failure here (undefined identifier, missing template key, etc.)
	// happens BEFORE ExecuteActivity ever fires the Before/After
	// ActivityExecution callbacks — so without this synthetic dispatch,
	// the step-progress tracker would never see the step at all and the
	// run's per-step view would show only the steps that completed
	// successfully before it. Emit a Before+After pair carrying the
	// error so the tracker records a {running -> failed} transition for
	// the step exactly as it would for an activity that crashed.
	params, err := p.buildStepParameters(ctx, step)
	if err != nil {
		p.dispatchParameterFailure(ctx, step, activityName, err)
		return nil, err
	}

	// Execute activity through the activityExecutor with branch-local state
	result, err := p.activityExecutor.ExecuteActivity(ctx, step.Name, p.id, activity, params, p.state)
	if err != nil {
		return nil, fmt.Errorf("activity %q execution failed on step %q: %w",
			activityName, step.Name, err)
	}
	return result, nil
}

// dispatchParameterFailure synthesises the Before/After ActivityExecution
// callback pair for a step whose parameter templates failed to evaluate.
// It is the only place a step transitions running->failed without ever
// reaching activityExecutor.ExecuteActivity, so it carries the same
// observability contract: trackers and consumer callbacks see one
// running event and one terminal failed event with the captured error.
func (p *branch) dispatchParameterFailure(ctx context.Context, step *Step, activityName string, err error) {
	if p.executionCallbacks == nil {
		return
	}
	now := time.Now()
	ev := &ActivityExecutionEvent{
		ExecutionID:  p.executionID,
		WorkflowName: p.workflow.Name(),
		BranchID:     p.id,
		StepName:     step.Name,
		ActivityName: activityName,
		StartTime:    now,
	}
	p.executionCallbacks.BeforeActivityExecution(ctx, ev)
	ev.EndTime = now
	ev.Error = err
	p.executionCallbacks.AfterActivityExecution(ctx, ev)
}

// executeStepWithRetry executes a step with retry logic using multiple retry configurations
func (p *branch) executeStepWithRetry(ctx context.Context, step *Step, retryConfigs []*RetryConfig) (any, error) {
	var lastErr error
	var activeRetryConfig *RetryConfig
	attempts := 0

	for {
		// Create timeout context using the active retry config's timeout
		stepCtx := ctx
		var cancel context.CancelFunc
		if activeRetryConfig != nil && activeRetryConfig.Timeout > 0 {
			stepCtx, cancel = context.WithTimeout(ctx, activeRetryConfig.Timeout)
		}

		result, err := p.executeStepOnce(stepCtx, step)

		if cancel != nil {
			cancel()
		}

		if err == nil {
			if lastErr != nil {
				p.logger.Info("step retry succeeded", "step_name", step.Name)
			}
			return result, nil
		}

		// Wait-unwind short-circuits retry entirely: it is a suspension,
		// not a failure, and must not consume retry budget. Explicit
		// bypass so a future retry config with ErrorEquals=["all"] can't
		// accidentally retry a suspended activity into an infinite loop.
		// Mirrors ErrFenceViolation's bypass via MatchesErrorType.
		if isWaitUnwind(err) {
			return nil, err
		}

		lastErr = err

		// If this is the first error, determine which retry configuration to use
		// for the entire retry sequence
		if activeRetryConfig == nil {
			activeRetryConfig = p.findMatchingRetryConfig(err, retryConfigs)
			if activeRetryConfig == nil {
				// No matching retry config found, return error immediately
				return nil, err
			}
		}

		// Check if we've exceeded max attempts for the active retry configuration
		if attempts >= activeRetryConfig.MaxRetries {
			p.logger.Info("step exceeded max retry attempts",
				"step_name", step.Name,
				"attempts", attempts+1,
				"max_attempts", activeRetryConfig.MaxRetries+1)
			return nil, err
		}

		// Increment attempt counter
		attempts++

		// Calculate and wait for backoff delay
		delay := p.calculateBackoffDelay(attempts, activeRetryConfig)

		p.logger.Info("retrying step",
			"step_name", step.Name,
			"attempt", attempts+1,
			"max_attempts", activeRetryConfig.MaxRetries+1,
			"delay", delay,
			"error_type", ClassifyError(err).Type)

		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(delay):
		}
	}
}

// handleBranching evaluates conditions and creates branch specs for branching
func (p *branch) handleBranching(ctx context.Context) ([]branchSpec, error) {
	edges := p.currentStep.Next
	if len(edges) == 0 {
		return nil, nil // No outgoing edges means this branch is complete
	}

	// Get the edge matching strategy for this step
	strategy := p.currentStep.GetEdgeMatchingStrategy()

	// Evaluate conditions and collect matching edges (state is now current)
	var matchingEdges []*Edge
	for _, edge := range edges {
		if edge.Condition == "" {
			matchingEdges = append(matchingEdges, edge)
		} else {
			match, err := p.evaluateCondition(ctx, edge.Condition)
			if err != nil {
				return nil, fmt.Errorf("failed to evaluate condition %q in step %q: %w",
					edge.Condition, p.currentStep.Name, err)
			}
			if match {
				matchingEdges = append(matchingEdges, edge)
			}
		}

		// If using "first" strategy and we found a match, stop here
		if strategy == EdgeMatchingFirst && len(matchingEdges) > 0 {
			break
		}
	}

	// Create branch specs for each matching edge, copying current branch's state
	var pathSpecs []branchSpec
	for _, edge := range matchingEdges {
		nextStep, ok := p.workflow.GetStep(edge.Step)
		if !ok {
			return nil, fmt.Errorf("next step not found: %s", edge.Step)
		}
		// Copy current branch's variables to the new branch
		pathSpecs = append(pathSpecs, branchSpec{
			Step:      nextStep,
			Variables: p.Variables(),
			Name:      edge.BranchName,
		})
	}
	return pathSpecs, nil
}

// evaluateCondition evaluates a workflow condition. Conditions are
// raw script expressions (e.g. "state.count > 3"). The literal strings
// "true" and "false" are recognized as shortcuts.
func (p *branch) evaluateCondition(ctx context.Context, condition string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(condition)) {
	case "true":
		return true, nil
	case "false":
		return false, nil
	}

	compiledScript, err := p.scriptCompiler.Compile(ctx, condition)
	if err != nil {
		return false, fmt.Errorf("failed to compile condition: %w", err)
	}
	result, err := compiledScript.Evaluate(ctx, p.buildScriptGlobals())
	if err != nil {
		return false, fmt.Errorf("failed to evaluate condition: %w", err)
	}
	return result.IsTruthy(), nil
}

// evaluateTemplateString evaluates a template and always returns a
// string. Used for signal topic names and other contexts that require
// a string result.
func (p *branch) evaluateTemplateString(ctx context.Context, template string) (string, error) {
	tmpl, err := script.NewTemplate(p.scriptCompiler, template)
	if err != nil {
		return "", fmt.Errorf("failed to compile template: %w", err)
	}
	return tmpl.EvalString(ctx, p.buildScriptGlobals())
}

// executeStepEach handles the execution of a step that has an each block
func (p *branch) executeStepEach(ctx context.Context, step *Step) (any, error) {
	each := step.Each

	// Resolve the items to iterate over
	items, err := p.resolveEachItems(ctx, each)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve each items: %w", err)
	}

	// Execute the step for each item and capture the results
	results := make([]any, 0, len(items))

	// Look up activity in registry
	activityName := step.Activity
	if activityName == "" {
		return nil, fmt.Errorf("no activity specified for step %q", step.Name)
	}

	activity, ok := p.activityRegistry[activityName]
	if !ok {
		return nil, fmt.Errorf("activity %q not found for step %q", activityName, step.Name)
	}

	// Remember the original value of the "as" variable
	var originalAsValue any
	var hadOriginalAs bool
	if each.As != "" {
		originalAsValue, hadOriginalAs = p.state.Get(each.As)
	}

	// restoreAs cleans up the iteration variable regardless of how the
	// loop exits (success or error).
	restoreAs := func() {
		if each.As == "" {
			return
		}
		if hadOriginalAs {
			p.state.Set(each.As, originalAsValue)
		} else {
			p.state.Delete(each.As)
		}
	}

	// Execute for each item
	for _, item := range items {
		// Prepare additional parameters for this iteration
		if each.As != "" {
			p.state.Set(each.As, item)
		}

		// Prepare parameters for this iteration. As in executeStepOnce,
		// a parameter-template failure happens before ExecuteActivity
		// can fire its Before/After callbacks, so synthesise the pair
		// here to keep the step-progress tracker honest.
		params, err := p.buildStepParameters(ctx, step)
		if err != nil {
			p.dispatchParameterFailure(ctx, step, activityName, err)
			restoreAs()
			return nil, err
		}

		// Execute activity for this item
		result, err := p.activityExecutor.ExecuteActivity(ctx, step.Name, p.id, activity, params, p.state)
		if err != nil {
			restoreAs()
			return nil, err
		}
		results = append(results, result)
	}

	restoreAs()

	// Store result directly in branch variables if specified
	if step.Store != "" {
		varName := strings.TrimPrefix(step.Store, "state.")
		p.state.Set(varName, results)
	}
	return results, nil
}

// resolveEachItems resolves the array of items for an Each block.
// A string value is treated as a raw script expression evaluated
// against the branch globals; array values are returned as-is.
func (p *branch) resolveEachItems(ctx context.Context, each *Each) ([]any, error) {
	if strArray, ok := each.Items.([]string); ok {
		items := make([]any, 0, len(strArray))
		for _, item := range strArray {
			items = append(items, item)
		}
		return items, nil
	}

	if items, ok := each.Items.([]any); ok {
		return items, nil
	}

	if codeStr, ok := each.Items.(string); ok {
		return p.evaluateExpression(ctx, codeStr)
	}

	return []any{each.Items}, nil
}

// evaluateExpression compiles and evaluates a raw script expression,
// returning its result as a slice.
func (p *branch) evaluateExpression(ctx context.Context, code string) ([]any, error) {
	compiledScript, err := p.scriptCompiler.Compile(ctx, code)
	if err != nil {
		p.logger.Error("failed to compile 'each' expression", "error", err)
		return nil, fmt.Errorf("failed to compile expression: %w", err)
	}
	result, err := compiledScript.Evaluate(ctx, p.buildScriptGlobals())
	if err != nil {
		p.logger.Error("failed to evaluate 'each' expression", "error", err)
		return nil, fmt.Errorf("failed to evaluate expression: %w", err)
	}
	return result.Items()
}

// calculateBackoffDelay calculates the backoff delay for retry attempts
func (p *branch) calculateBackoffDelay(attempt int, retryConfig *RetryConfig) time.Duration {
	baseDelay := retryConfig.BaseDelay
	if baseDelay <= 0 {
		baseDelay = 1 * time.Second // Default base delay
	}

	backoffRate := retryConfig.BackoffRate
	if backoffRate <= 0 {
		backoffRate = 2.0 // Default backoff rate
	}

	// Exponential backoff
	delay := time.Duration(float64(baseDelay) * float64(int64(1)<<(attempt-1)))
	if backoffRate != 2.0 {
		// Use custom backoff rate instead of power of 2
		multiplier := 1.0
		for i := 1; i < attempt; i++ {
			multiplier *= backoffRate
		}
		delay = time.Duration(float64(baseDelay) * multiplier)
	}

	// Apply max delay cap if configured
	if retryConfig.MaxDelay > 0 && delay > retryConfig.MaxDelay {
		delay = retryConfig.MaxDelay
	}

	// Add jitter if configured
	if retryConfig.JitterStrategy == JitterFull {
		// Full jitter: randomize between 0 and calculated delay
		jitterRange := float64(delay)
		delay = time.Duration(rand.Float64() * jitterRange)
	}

	if delay < 0 {
		delay = baseDelay
	}

	return delay
}

// findMatchingRetryConfig finds the first retry configuration that matches the given error
func (p *branch) findMatchingRetryConfig(err error, retryConfigs []*RetryConfig) *RetryConfig {
	for _, config := range retryConfigs {
		// If no error types are explicitly specified, that equates to ErrorTypeAll
		if len(config.ErrorEquals) == 0 {
			if MatchesErrorType(err, ErrorTypeAll) {
				return config
			}
		}
		// Check if error matches any of the specified error types
		for _, errorType := range config.ErrorEquals {
			if MatchesErrorType(err, errorType) {
				return config
			}
		}
	}
	return nil
}

// executeCatchHandler executes catch handling logic when an error occurs
func (p *branch) executeCatchHandler(step *Step, err error) (any, error) {
	wErr := ClassifyError(err)
	// Find matching catch configuration
	for _, catchConfig := range step.Catch {
		for _, errorType := range catchConfig.ErrorEquals {
			if MatchesErrorType(err, errorType) {
				// Found a matching catch handler
				p.logger.Info("executing catch handler",
					"step_name", step.Name,
					"error_type", wErr.Type,
					"next_step", catchConfig.Next)

				// Create error output
				errorOutput := wErr.ToErrorOutput()

				// Store error if specified
				if catchConfig.Store != "" {
					resultPath := strings.TrimPrefix(catchConfig.Store, "state.")
					if resultPath != "" {
						p.state.Set(resultPath, errorOutput)
					}
				}

				// Transition to the catch step
				nextStep, ok := p.workflow.GetStep(catchConfig.Next)
				if !ok {
					return nil, fmt.Errorf("catch handler step %q not found", catchConfig.Next)
				}

				// Update current step to the catch handler step
				p.currentStep = nextStep

				// Return a special marker to indicate successful catch handling
				// The main execution loop will continue with the new step
				return catchErrorSentinel, nil
			}
		}
	}
	// No matching catch handler found
	return nil, err
}

// buildScriptGlobals creates globals used for script execution
func (p *branch) buildScriptGlobals() map[string]any {
	p.state.mu.RLock()
	inputs := copyMap(p.state.inputs)
	variables := copyMap(p.state.variables)
	p.state.mu.RUnlock()
	return map[string]any{
		"inputs": inputs,
		"state":  variables,
	}
}

// buildStepParameters creates a parameter map by evaluating templates and script expressions
func (p *branch) buildStepParameters(ctx context.Context, step *Step) (map[string]interface{}, error) {
	params := make(map[string]interface{}, len(step.Parameters))
	for name, value := range step.Parameters {
		evaluated, err := p.evaluateParameterValue(ctx, value, step.Name, name)
		if err != nil {
			return nil, err
		}
		params[name] = evaluated
	}
	return params, nil
}

// evaluateParameterValue evaluates a parameter value. String values
// containing ${...} templates are evaluated with contextual type
// inference: a value that is exactly one ${expr} token (ignoring
// surrounding whitespace) preserves the expression's typed result;
// otherwise the result is a string built by interpolating each
// token's stringified value.
func (p *branch) evaluateParameterValue(ctx context.Context, value interface{}, stepName, paramName string) (interface{}, error) {
	if mapValue, ok := value.(map[string]any); ok {
		outMap := make(map[string]any, len(mapValue))
		for key, inner := range mapValue {
			evaluated, err := p.evaluateParameterValue(ctx, inner, stepName, key)
			if err != nil {
				return nil, err
			}
			outMap[key] = evaluated
		}
		return outMap, nil
	}
	// Recurse into slices so ${…} templates inside parameters like
	// "evidence": [{"label":"…","value":"${state.x}"}] expand the
	// same way they do inside maps. Without this, a slice falls
	// through to the (value.(string)) assertion below — fails — and
	// the slice is returned verbatim with literal "${…}" inside.
	if sliceValue, ok := value.([]any); ok {
		outSlice := make([]any, len(sliceValue))
		for i, inner := range sliceValue {
			evaluated, err := p.evaluateParameterValue(ctx, inner, stepName, paramName)
			if err != nil {
				return nil, err
			}
			outSlice[i] = evaluated
		}
		return outSlice, nil
	}

	strValue, ok := value.(string)
	if !ok {
		return value, nil
	}
	if !strings.Contains(strValue, "${") {
		return value, nil
	}

	tmpl, err := script.NewTemplate(p.scriptCompiler, strValue)
	if err != nil {
		return nil, fmt.Errorf("failed to compile parameter template %q in step %q: %w",
			paramName, stepName, err)
	}
	evaluated, err := tmpl.Eval(ctx, p.buildScriptGlobals())
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate parameter template %q in step %q: %w",
			paramName, stepName, err)
	}
	return evaluated, nil
}
